name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          maven-version: '3.8.4'  # Specify the version of Maven you want to use
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean package checkstyle:check findbugs:check jacoco:report

      - name: Run Tests
        run: mvn surefire:test
